# Generated by Django 5.0.7 on 2024-07-29 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作業所名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10,11}$')], verbose_name='電話番号')),
            ],
        ),
    ]
