# Generated by Django 5.0.7 on 2024-07-29 06:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9]{14}$')], verbose_name='商品コード')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.CharField(max_length=400, verbose_name='商品説明')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='重量')),
                ('size', models.CharField(blank=True, max_length=200, null=True, verbose_name='サイズ')),
                ('price', models.PositiveIntegerField(verbose_name='税込み価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.productcategory', verbose_name='カテゴリー')),
            ],
        ),
    ]
