# Generated by Django 5.0.7 on 2024-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0002_productcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='jewelstock.productcategory', verbose_name='カテゴリー'),
        ),
    ]
