# Generated by Django 5.0.7 on 2024-07-29 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会社名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10,11}$')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200, verbose_name='作業')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.workplace', verbose_name='作業所')),
            ],
        ),
    ]
