# Generated by Django 5.0.7 on 2024-07-30 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0005_material_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateField(blank=True, default=None, null=True, verbose_name='製造日')),
                ('sold_date', models.DateField(blank=True, default=None, null=True, verbose_name='売却日')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.product', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='個数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.material', verbose_name='材料')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_material',
            field=models.ManyToManyField(through='jewelstock.ItemMaterial', to='jewelstock.material'),
        ),
    ]
