# Generated by Django 5.0.7 on 2024-07-30 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0006_item_itemmaterial_item_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_material',
            field=models.ManyToManyField(through='jewelstock.ItemMaterial', to='jewelstock.material', verbose_name='材料'),
        ),
        migrations.AlterField(
            model_name='itemmaterial',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='アイテム'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_material', models.CharField(max_length=500, verbose_name='注文材料')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='発注日時')),
                ('delivery_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='納品日')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelstock.workplace', verbose_name='発注場所')),
            ],
        ),
    ]
