# Generated by Django 5.0.7 on 2024-07-30 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0007_alter_item_item_material_alter_itemmaterial_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='開始日')),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='期限')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='終了日')),
                ('confirmor', models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('削除されたユーザー'), to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.item', verbose_name='アイテム')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelstock.process', verbose_name='工程')),
            ],
        ),
    ]
