# Generated by Django 5.0.7 on 2024-07-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelstock', '0009_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='Workplace',
            new_name='workplace',
        ),
    ]
